version: "3.9"
services:
  app:
    image: "mcr.microsoft.com/vscode/devcontainers/javascript-node:16"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
    environment:
      - FHIR_TARGET=http://localhost:8080
      - FHIR_PATH=/fhir
      - VUE_APP_FHIR_URL=http://localhost:8080/fhir
  hapi:
    volumes:
      - ./config/hapi:/etc/hapi
      - hapi:/data/hapi
    environment:
      SPRING_CONFIG_ADDITIONAL-LOCATION: /etc/hapi/application.yaml
  nginx:
    image: nginx
    volumes:
      - ./config/nginx:/etc/nginx/templates
    ports:
      - 8080:8080
    environment:
      - APP_URL=http://app:9000
      - FHIR_URL=http://hapi:8080/hapi/fhir
      - HAPI_URL=http://hapi:8080
volumes:
  hapi:
