version: "3.9"
services:
  app:
    image: "mcr.microsoft.com/vscode/devcontainers/javascript-node:16"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
  hapi:
    ports:
      - "80:8080"
    volumes:
      - hapi:/data/hapi
volumes:
  hapi:
